title: Kelvin Zeng # your name (or website title) here
logo: "/images/pfp.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Detail-oriented physics graduate looking for rewarding experiences and is excited contribute with my strong analytical skills. 
  I have solid experience in working with large datasets and an excellent team player that strives for co-improvement along with data-driven questioning. 
  I'm also a self-starter needing little oversight, have a strong quantitative and statistical background with some knowledge in finance.  
  <br><br>
  Current project: [8 weeks of SQL challenge]
  <br><br>
  <a href="https://www.linkedin.com/in/kelvinwz/">View My LinkedIn Profile</a> 
  <Br><Br>
  <a href="https://www.kaggle.com/kelvinzeng">View My Kaggle Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
